name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: ubuntu-latest-arm64
            arch: arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libglib2.0-dev libgtk-3-dev libwayland-dev libasound2-dev libgirepository1.0-dev libgraphene-1.0-dev
      - name: Build the app
        run: |
          mkdir -p .bin
          export GO111MODULE=on
          export GOBIN=$(pwd)/.bin
          go build -pgo default.pgo -tags wayland -trimpath -ldflags="-s -w" -o $GOBIN/play-timer-${{ matrix.arch }} ./cmd/main.go
      - name: Verify build output
        run: |
          if [ ! -f .bin/play-timer-${{ matrix.arch }} ]; then
            echo "Build failed: play-timer-${{ matrix.arch }} binary not found"
            exit 1
